name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SYMBOL_VERSION: "3"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_UPDATED_DATE: "False"
          DEBUG_LOGGING: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
